export type SignatureMethod =
  | 'no_bankid_mobile'
  | 'no_bankid_netcentric'
  | 'no_buypass'
  | 'se_bankid'
  | 'dk_nemid'
  | 'fi_tupas'
  | 'fi_mobiilivarmenne'
  | 'fi_eid'
  | 'sms_otp'
  | 'unknown'
